# training parameters
vocab_size: 128
num_nearest_neibor: 41
batch_size: 256
num_epochs: 10000
learning_rate: 0.001
reschedule: True
enforce: True
temp_anneling: False
temperature: 10  # Temperature for Boltzmann distribution
use_wnb: False

# sampling parameters
div: 10
sample_step: 0.1